# Generated by Django 6.0.4 on 2026-05-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_carbrand_remove_subcategory_category_carmodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarBrand',
        ),
        migrations.DeleteModel(
            name='CarModel',
        ),
    ]
